package com.zhihuiji.backend.infrastructure.db;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import org.junit.jupiter.api.Test;

/**
 * V32 agent_context_checkpoints 迁移测试。
 *
 * <p>直接执行迁移 DDL，验证：
 * 1. 表与索引可创建（H2 PostgreSQL 模式与 SQLite 内存均验证）。
 * 2. 唯一约束 (owner, conversation, boundary, policy_version, revision) 阻止
 *    同一边界重复有效检查点。
 * 3. 失效后提升 revision 允许重新生成同一边界的有效检查点。
 * 4. 不同 owner 允许相同的 boundary + revision（owner 隔离）。
 * 5. conversation 删除级联清理检查点。
 *
 * <p>本测试只执行迁移 SQL，不替代 PostgreSQL 生产查询计划（另行 Blocked/Deferred）。
 */
class V32AgentContextCheckpointsSqlTest {

    private static final String V32_PATH =
        "src/main/resources/db/migration/V32__agent_context_checkpoints.sql";

    private static final String CONVERSATIONS_DDL = """
        CREATE TABLE IF NOT EXISTS agent_conversations (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            owner_user_id BIGINT NOT NULL,
            title VARCHAR(255),
            created_at BIGINT NOT NULL,
            updated_at BIGINT NOT NULL
        );
        """;

    private String readV32() throws Exception {
        return Files.readString(Path.of(V32_PATH));
    }

    private void createSchema(Connection connection) throws Exception {
        try (Statement statement = connection.createStatement()) {
            statement.execute(CONVERSATIONS_DDL);
            statement.execute(readV32());
        }
        // 种子会话：外键要求 conversation_id 必须存在。
        try (Statement statement = connection.createStatement()) {
            statement.execute("""
                INSERT INTO agent_conversations (id, owner_user_id, title, created_at, updated_at)
                VALUES (201, 1, '会话A', 1, 1), (202, 2, '会话B', 1, 1)
                """);
        }
    }

    private Connection h2Connection() throws Exception {
        // 每个测试使用独立内存库，避免 DB_CLOSE_DELAY=-1 导致跨测试残留数据。
        String dbName = "ctx_checkpoint_v32_" + System.nanoTime();
        Connection connection = DriverManager.getConnection(
            "jdbc:h2:mem:" + dbName + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", ""
        );
        createSchema(connection);
        return connection;
    }

    private long insertCheckpoint(Connection connection, long owner, long conversation,
        long boundary, int revision, String status) throws SQLException {
        try (PreparedStatement ps = connection.prepareStatement("""
                INSERT INTO agent_context_checkpoints (
                    owner_user_id, conversation_id, source_boundary_message_id,
                    source_message_count, summary_body, summary_version,
                    context_policy_version, tool_schema_version, revision,
                    quality, status, created_at, updated_at
                ) VALUES (?, ?, ?, 6, ?, 1, 1, 1, ?, 'deterministic', ?, 1000, 1000)
                """)) {
            ps.setLong(1, owner);
            ps.setLong(2, conversation);
            ps.setLong(3, boundary);
            ps.setString(4, "{\"summary_version\":1}");
            ps.setInt(5, revision);
            ps.setString(6, status);
            ps.executeUpdate();
        }
        try (Statement statement = connection.createStatement();
             ResultSet rs = statement.executeQuery("SELECT MAX(id) FROM agent_context_checkpoints")) {
            rs.next();
            return rs.getLong(1);
        }
    }

    private void invalidate(Connection connection, long owner, long conversation) throws SQLException {
        try (PreparedStatement ps = connection.prepareStatement("""
                UPDATE agent_context_checkpoints SET status = 'invalidated',
                    invalidated_at = 2000, updated_at = 2000
                WHERE owner_user_id = ? AND conversation_id = ? AND status = 'active'
                """)) {
            ps.setLong(1, owner);
            ps.setLong(2, conversation);
            ps.executeUpdate();
        }
    }

    @Test
    void h2PostgresModeCreatesTableAndRejectsDuplicateBoundary() throws Exception {
        try (Connection connection = h2Connection()) {
            insertCheckpoint(connection, 1L, 201L, 100L, 1, "active");
            // 同 owner/conversation/boundary/policy/revision 重复插入违反唯一约束。
            assertThrows(SQLException.class,
                () -> insertCheckpoint(connection, 1L, 201L, 100L, 1, "active"));
        }
    }

    @Test
    void h2PostgresModeAllowsRegenerationAfterInvalidationWithHigherRevision() throws Exception {
        try (Connection connection = h2Connection()) {
            insertCheckpoint(connection, 1L, 201L, 100L, 1, "active");
            invalidate(connection, 1L, 201L);
            // 同一边界失效后，提升 revision 允许重新生成有效检查点。
            insertCheckpoint(connection, 1L, 201L, 100L, 2, "active");
            try (Statement statement = connection.createStatement();
                 ResultSet rs = statement.executeQuery(
                     "SELECT COUNT(*) FROM agent_context_checkpoints WHERE status = 'active'")) {
                rs.next();
                assertEquals(1, rs.getInt(1));
            }
        }
    }

    @Test
    void h2PostgresModeScopesUniqueConstraintPerOwner() throws Exception {
        try (Connection connection = h2Connection()) {
            insertCheckpoint(connection, 1L, 201L, 100L, 1, "active");
            // 不同 owner 允许相同 boundary + revision（owner 隔离）。
            insertCheckpoint(connection, 2L, 202L, 100L, 1, "active");
            try (Statement statement = connection.createStatement();
                 ResultSet rs = statement.executeQuery(
                     "SELECT COUNT(*) FROM agent_context_checkpoints WHERE owner_user_id = 2")) {
                rs.next();
                assertEquals(1, rs.getInt(1));
            }
        }
    }

    @Test
    void h2PostgresModeCascadesDeleteOnConversationRemoval() throws Exception {
        try (Connection connection = h2Connection()) {
            insertCheckpoint(connection, 1L, 201L, 100L, 1, "active");
            try (PreparedStatement ps = connection.prepareStatement(
                "DELETE FROM agent_conversations WHERE id = 201")) {
                ps.executeUpdate();
            }
            try (Statement statement = connection.createStatement();
                 ResultSet rs = statement.executeQuery(
                     "SELECT COUNT(*) FROM agent_context_checkpoints")) {
                rs.next();
                assertEquals(0, rs.getInt(1), "会话删除应级联清理检查点");
            }
        }
    }

    /**
     * SQLite 迁移兼容性证据（Blocked 记录）。
     *
     * <p>后端本地开发使用 H2（PostgreSQL 模式）、生产使用 PostgreSQL；SQLite 不是
     * Agent 表的运行时数据库。当前 sqlite-jdbc 内置 SQLite 版本无法解析
     * {@code BIGINT GENERATED BY DEFAULT AS IDENTITY} 语法，因此 V32 迁移 SQL
     * 无法直接在 SQLite 上执行。本测试确定性记录该限制，不伪造 SQLite 迁移通过。
     */
    @Test
    void sqliteCannotExecuteIdentitySyntaxIsRecordedAsBlocked() throws Exception {
        try (Connection connection = DriverManager.getConnection("jdbc:sqlite::memory:")) {
            try (Statement statement = connection.createStatement()) {
                statement.execute("PRAGMA foreign_keys = ON");
                statement.execute("""
                    CREATE TABLE agent_conversations (
                        id INTEGER PRIMARY KEY,
                        owner_user_id BIGINT NOT NULL,
                        title VARCHAR(255),
                        created_at BIGINT NOT NULL,
                        updated_at BIGINT NOT NULL
                    )
                    """);
            }
            SQLException failure = assertThrows(SQLException.class, () -> {
                try (Statement statement = connection.createStatement()) {
                    statement.execute(readV32());
                }
            });
            String message = failure.getMessage() == null ? "" : failure.getMessage();
            assertTrue(message.toLowerCase().contains("syntax error"),
                "SQLite 应因 IDENTITY 语法拒绝 V32 DDL，实际错误：" + message);
            // 表未被创建，迁移在 SQLite 上不可执行（Blocked）。
            try (Statement statement = connection.createStatement();
                 ResultSet rs = statement.executeQuery(
                     "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='agent_context_checkpoints'")) {
                rs.next();
                assertEquals(0, rs.getInt(1));
            }
        }
    }

    @Test
    void migrationDeclaresIndexesAndForeignKey() throws Exception {
        String sql = readV32();
        assertTrue(sql.contains("idx_agent_context_checkpoints_owner_conv_boundary"));
        assertTrue(sql.contains("idx_agent_context_checkpoints_owner_conv_status"));
        assertTrue(sql.contains("uk_agent_context_checkpoints_boundary_revision"));
        assertTrue(sql.contains("ON DELETE CASCADE"));
        assertTrue(sql.contains("FOREIGN KEY (conversation_id) REFERENCES agent_conversations(id)"));
    }
}
