package com.zhihuiji.backend.infrastructure.db;

import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import org.junit.jupiter.api.Test;

class V41AdminAnonymousDenialSqlTest {
    @Test
    void migrationAllowsOnlyExplicitAnonymousAuditRowsToOmitAdminId() throws Exception {
        String sql = Files.readString(Path.of(
            "src/main/resources/db/migration/V41__admin_anonymous_denial_audit.sql"
        )).toLowerCase();

        assertTrue(sql.contains("alter column admin_user_id drop not null"));
        assertTrue(sql.contains("ck_admin_audit_actor_identity"));
        assertTrue(sql.contains("admin_user_id is not null"));
        assertTrue(sql.contains("role_code = 'anonymous'"));
        assertTrue(sql.contains("action = 'admin.access.denied'"));
        assertTrue(sql.contains("result = 'denied'"));
    }

    @Test
    void databaseConstraintRejectsAnonymousRowsForOtherActions() throws Exception {
        String dbName = "admin_audit_v41_" + System.nanoTime();
        try (Connection connection = DriverManager.getConnection(
            "jdbc:h2:mem:" + dbName + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "")) {
            try (Statement statement = connection.createStatement()) {
                statement.execute("""
                    CREATE TABLE admin_audit_events (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        admin_user_id BIGINT,
                        role_code VARCHAR(32) NOT NULL,
                        action VARCHAR(64) NOT NULL,
                        result VARCHAR(32) NOT NULL
                    )
                    """);
                // This creates the V41 post-migration shape so the CHECK itself
                // is exercised without changing the production SQL dialect.
                statement.execute("""
                    ALTER TABLE admin_audit_events
                    ADD CONSTRAINT ck_admin_audit_actor_identity
                    CHECK (
                        admin_user_id IS NOT NULL
                        OR (role_code = 'ANONYMOUS' AND action = 'admin.access.denied' AND result = 'DENIED')
                    )
                    """);
                statement.execute("INSERT INTO admin_audit_events (admin_user_id, role_code, action, result) "
                    + "VALUES (NULL, 'ANONYMOUS', 'admin.access.denied', 'DENIED')");
                assertThrows(SQLException.class, () -> statement.execute(
                    "INSERT INTO admin_audit_events (admin_user_id, role_code, action, result) "
                        + "VALUES (NULL, 'ANONYMOUS', 'admin.audit.read', 'SUCCESS')"));
            }
        }
    }
}
