CREATE TABLE IF NOT EXISTS sales_returns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    return_no VARCHAR(64) NOT NULL,
    original_order_id BIGINT,
    customer_id BIGINT,
    customer_name VARCHAR(128),
    total_amount DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    refund_amount DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    status INTEGER NOT NULL DEFAULT 0,
    notes VARCHAR(255),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

ALTER TABLE sales_returns ADD CONSTRAINT uk_sales_returns_owner_return_no UNIQUE (owner_user_id, return_no);
CREATE INDEX idx_sales_returns_owner ON sales_returns(owner_user_id);
CREATE INDEX idx_sales_returns_original_order ON sales_returns(original_order_id);
CREATE INDEX idx_sales_returns_status ON sales_returns(owner_user_id, status);

CREATE TABLE IF NOT EXISTS sales_return_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    return_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_code VARCHAR(64),
    product_name VARCHAR(128),
    quantity DOUBLE PRECISION NOT NULL,
    unit_price DOUBLE PRECISION NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    created_at BIGINT NOT NULL
);

CREATE INDEX idx_sales_return_items_owner ON sales_return_items(owner_user_id);
CREATE INDEX idx_sales_return_items_return ON sales_return_items(return_id);

CREATE TABLE IF NOT EXISTS purchase_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    receipt_no VARCHAR(64) NOT NULL,
    purchase_order_id BIGINT,
    supplier_id BIGINT,
    supplier_name VARCHAR(128),
    total_amount DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    status INTEGER NOT NULL DEFAULT 0,
    notes VARCHAR(255),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

ALTER TABLE purchase_receipts ADD CONSTRAINT uk_purchase_receipts_owner_receipt_no UNIQUE (owner_user_id, receipt_no);
CREATE INDEX idx_purchase_receipts_owner ON purchase_receipts(owner_user_id);
CREATE INDEX idx_purchase_receipts_purchase_order ON purchase_receipts(purchase_order_id);
CREATE INDEX idx_purchase_receipts_status ON purchase_receipts(owner_user_id, status);

CREATE TABLE IF NOT EXISTS purchase_receipt_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    receipt_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_code VARCHAR(64),
    product_name VARCHAR(128),
    quantity DOUBLE PRECISION NOT NULL,
    unit_cost DOUBLE PRECISION NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    created_at BIGINT NOT NULL
);

CREATE INDEX idx_purchase_receipt_items_owner ON purchase_receipt_items(owner_user_id);
CREATE INDEX idx_purchase_receipt_items_receipt ON purchase_receipt_items(receipt_id);

ALTER TABLE pay_orders ADD COLUMN IF NOT EXISTS account_id BIGINT;
CREATE INDEX idx_pay_orders_account ON pay_orders(account_id);

ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS paid_amount DOUBLE PRECISION NOT NULL DEFAULT 0.0;
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS received_amount DOUBLE PRECISION NOT NULL DEFAULT 0.0;
