CREATE TABLE IF NOT EXISTS stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    store_name VARCHAR(128) NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_stores_owner_user_id ON stores(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_stores_owner_user_id ON stores(owner_user_id);

CREATE TABLE IF NOT EXISTS store_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role_code VARCHAR(32) NOT NULL,
    title VARCHAR(64) NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_store_memberships_owner_user ON store_memberships(owner_user_id, user_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_store_memberships_user_id ON store_memberships(user_id);
CREATE INDEX IF NOT EXISTS idx_store_memberships_owner_user_id ON store_memberships(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_store_memberships_store_id ON store_memberships(store_id);
