-- V27: durable ordered change stream and store-scoped idempotency/deletions.
-- Existing V26 rows remain readable; new rows are always written with store_id.
ALTER TABLE sync_operation_log ADD COLUMN IF NOT EXISTS store_id BIGINT;
ALTER TABLE sync_tombstones ADD COLUMN IF NOT EXISTS store_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_sync_operation_log_owner_store_processed
    ON sync_operation_log (owner_user_id, store_id, processed_at);
CREATE INDEX IF NOT EXISTS idx_sync_tombstones_owner_store_deleted
    ON sync_tombstones (owner_user_id, store_id, deleted_at);

CREATE TABLE IF NOT EXISTS sync_change_log (
    sequence_no BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    entity_type VARCHAR(64) NOT NULL,
    entity_id VARCHAR(64) NOT NULL,
    operation VARCHAR(16) NOT NULL,
    payload TEXT,
    sync_version BIGINT,
    operation_id VARCHAR(128),
    changed_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sync_change_log_owner_store_sequence
    ON sync_change_log (owner_user_id, store_id, sequence_no);
CREATE INDEX IF NOT EXISTS idx_sync_change_log_owner_store_entity
    ON sync_change_log (owner_user_id, store_id, entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_sync_change_log_owner_store_changed
    ON sync_change_log (owner_user_id, store_id, changed_at, sequence_no);
