-- Context window compaction checkpoints (plan 6.7).
-- Stores owner + conversation-scoped summaries used to compress completed
-- conversation turns so that future model requests stay within the
-- provider token budget. Checkpoints only carry completion-judgement
-- fields; credentials, full auth payloads and unrelated customer data
-- must never be persisted here.
CREATE TABLE IF NOT EXISTS agent_context_checkpoints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    conversation_id BIGINT NOT NULL,
    source_boundary_message_id BIGINT NOT NULL,
    source_message_count INTEGER NOT NULL,
    summary_body TEXT NOT NULL,
    summary_version INTEGER NOT NULL DEFAULT 1,
    context_policy_version INTEGER NOT NULL DEFAULT 1,
    tool_schema_version INTEGER NOT NULL DEFAULT 1,
    revision INTEGER NOT NULL DEFAULT 1,
    quality VARCHAR(32) NOT NULL DEFAULT 'deterministic',
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    model_name VARCHAR(128),
    estimated_input_tokens INTEGER,
    estimated_output_tokens INTEGER,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    invalidated_at BIGINT,
    invalidation_reason VARCHAR(128),
    CONSTRAINT fk_agent_context_checkpoints_conversation
        FOREIGN KEY (conversation_id) REFERENCES agent_conversations(id) ON DELETE CASCADE
);

-- Active checkpoint lookup: owner + conversation + boundary.
CREATE INDEX IF NOT EXISTS idx_agent_context_checkpoints_owner_conv_boundary
    ON agent_context_checkpoints(owner_user_id, conversation_id, source_boundary_message_id);

-- Invalidation / TTL scan by status.
CREATE INDEX IF NOT EXISTS idx_agent_context_checkpoints_owner_conv_status
    ON agent_context_checkpoints(owner_user_id, conversation_id, status, updated_at DESC);

-- Concurrent compaction guard: only one active revision per boundary.
CREATE UNIQUE INDEX IF NOT EXISTS uk_agent_context_checkpoints_boundary_revision
    ON agent_context_checkpoints(owner_user_id, conversation_id, source_boundary_message_id, context_policy_version, revision);
