-- Server-owned administrator identity and visibility grants.
-- Store membership role_code is deliberately not used for administrator access.
CREATE TABLE IF NOT EXISTS admin_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    role_code VARCHAR(32) NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    version BIGINT NOT NULL DEFAULT 1,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT fk_admin_accounts_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT ck_admin_accounts_role CHECK (role_code IN ('SUPER_ADMIN', 'AUDIT_OBSERVER'))
);

CREATE TABLE IF NOT EXISTS admin_scope_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_account_id BIGINT NOT NULL,
    scope_type VARCHAR(16) NOT NULL,
    owner_user_id BIGINT,
    store_id BIGINT,
    granted_by BIGINT,
    status INTEGER NOT NULL DEFAULT 1,
    created_at BIGINT NOT NULL,
    CONSTRAINT fk_admin_scope_account FOREIGN KEY (admin_account_id) REFERENCES admin_accounts(id) ON DELETE CASCADE,
    CONSTRAINT fk_admin_scope_owner FOREIGN KEY (owner_user_id) REFERENCES users(id),
    CONSTRAINT fk_admin_scope_store FOREIGN KEY (store_id) REFERENCES stores(id),
    CONSTRAINT ck_admin_scope_type CHECK (scope_type IN ('OWNER', 'STORE')),
    CONSTRAINT ck_admin_scope_target CHECK (owner_user_id IS NOT NULL OR store_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_admin_scope_account_status ON admin_scope_grants(admin_account_id, status);
CREATE INDEX IF NOT EXISTS idx_admin_scope_owner ON admin_scope_grants(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_admin_scope_store ON admin_scope_grants(store_id);
