-- Administrator audit, configuration, export and retention state.
-- Payload columns deliberately contain summaries only; secrets are never stored.
CREATE TABLE IF NOT EXISTS admin_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(128) NOT NULL UNIQUE,
    admin_user_id BIGINT NOT NULL,
    role_code VARCHAR(32) NOT NULL,
    action VARCHAR(64) NOT NULL,
    resource_type VARCHAR(64),
    resource_id VARCHAR(128),
    owner_user_id BIGINT,
    store_id BIGINT,
    source_ip VARCHAR(64),
    user_agent_summary VARCHAR(256),
    request_id VARCHAR(128),
    result VARCHAR(32) NOT NULL,
    reason VARCHAR(512),
    summary VARCHAR(1000),
    idempotency_key VARCHAR(128),
    idempotency_payload_hash VARCHAR(64),
    occurred_at BIGINT NOT NULL,
    CONSTRAINT fk_admin_audit_admin FOREIGN KEY (admin_user_id) REFERENCES users(id),
    CONSTRAINT fk_admin_audit_owner FOREIGN KEY (owner_user_id) REFERENCES users(id),
    CONSTRAINT fk_admin_audit_store FOREIGN KEY (store_id) REFERENCES stores(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_admin_audit_admin_idempotency
    ON admin_audit_events(admin_user_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_admin_audit_occurred ON admin_audit_events(occurred_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_admin_audit_admin_occurred ON admin_audit_events(admin_user_id, occurred_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_admin_audit_scope_occurred ON admin_audit_events(owner_user_id, store_id, occurred_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS admin_agent_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id VARCHAR(128),
    agent_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    enabled_tools_json TEXT NOT NULL DEFAULT '[]',
    scope_owner_user_id BIGINT,
    scope_store_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    effective_state VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    effective_at BIGINT,
    updated_by BIGINT,
    idempotency_key VARCHAR(128),
    idempotency_payload_hash VARCHAR(64),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT fk_admin_config_owner FOREIGN KEY (scope_owner_user_id) REFERENCES users(id),
    CONSTRAINT fk_admin_config_store FOREIGN KEY (scope_store_id) REFERENCES stores(id),
    CONSTRAINT fk_admin_config_actor FOREIGN KEY (updated_by) REFERENCES users(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_admin_agent_config_scope
    ON admin_agent_configs(scope_owner_user_id, scope_store_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_admin_agent_config_idempotency
    ON admin_agent_configs(idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS admin_export_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    export_id VARCHAR(128) NOT NULL UNIQUE,
    admin_user_id BIGINT NOT NULL,
    export_type VARCHAR(64) NOT NULL,
    fields_json TEXT NOT NULL,
    scope_owner_user_id BIGINT,
    scope_store_id BIGINT,
    status VARCHAR(32) NOT NULL,
    content_csv TEXT,
    error_summary VARCHAR(512),
    idempotency_key VARCHAR(128),
    idempotency_payload_hash VARCHAR(64),
    created_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    completed_at BIGINT,
    downloaded_at BIGINT,
    download_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_admin_export_admin FOREIGN KEY (admin_user_id) REFERENCES users(id),
    CONSTRAINT fk_admin_export_owner FOREIGN KEY (scope_owner_user_id) REFERENCES users(id),
    CONSTRAINT fk_admin_export_store FOREIGN KEY (scope_store_id) REFERENCES stores(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_admin_export_admin_idempotency
    ON admin_export_jobs(admin_user_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_admin_export_admin_status ON admin_export_jobs(admin_user_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_export_expiry ON admin_export_jobs(expires_at, status);

CREATE TABLE IF NOT EXISTS admin_retention_policies (
    id BIGINT PRIMARY KEY,
    audit_days INTEGER NOT NULL,
    message_days INTEGER NOT NULL,
    tool_result_days INTEGER NOT NULL,
    metrics_days INTEGER NOT NULL,
    content_mode VARCHAR(32) NOT NULL DEFAULT 'REDACTED',
    version BIGINT NOT NULL DEFAULT 0,
    effective_at BIGINT NOT NULL,
    updated_by BIGINT,
    idempotency_key VARCHAR(128),
    idempotency_payload_hash VARCHAR(64),
    reason VARCHAR(512),
    CONSTRAINT fk_admin_retention_actor FOREIGN KEY (updated_by) REFERENCES users(id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_admin_retention_idempotency
    ON admin_retention_policies(idempotency_key)
    WHERE idempotency_key IS NOT NULL;
