CREATE TABLE IF NOT EXISTS product_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS product_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    name VARCHAR(64) NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS partner_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    partner_type VARCHAR(16) NOT NULL,
    name VARCHAR(128) NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS partner_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    partner_type VARCHAR(16) NOT NULL,
    partner_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    phone VARCHAR(32),
    title VARCHAR(64),
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

ALTER TABLE products ADD COLUMN IF NOT EXISTS category_id BIGINT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS unit_id BIGINT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS group_id BIGINT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS contact_name VARCHAR(128);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(32);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS group_id BIGINT;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS contact_name VARCHAR(128);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(32);

INSERT INTO product_categories (owner_user_id, name, status, sort_order, created_at, updated_at)
SELECT DISTINCT p.owner_user_id, p.category, 1, 0, COALESCE(p.created_at, 1717353600000), COALESCE(p.updated_at, 1717353600000)
FROM products p
WHERE p.category IS NOT NULL
  AND TRIM(p.category) <> ''
  AND NOT EXISTS (
    SELECT 1 FROM product_categories c
    WHERE c.owner_user_id = p.owner_user_id
      AND c.name = p.category
  );

INSERT INTO product_units (owner_user_id, name, status, sort_order, created_at, updated_at)
SELECT DISTINCT p.owner_user_id, p.unit, 1, 0, COALESCE(p.created_at, 1717353600000), COALESCE(p.updated_at, 1717353600000)
FROM products p
WHERE p.unit IS NOT NULL
  AND TRIM(p.unit) <> ''
  AND NOT EXISTS (
    SELECT 1 FROM product_units u
    WHERE u.owner_user_id = p.owner_user_id
      AND u.name = p.unit
  );

UPDATE products p
SET category_id = (
    SELECT c.id
    FROM product_categories c
    WHERE c.owner_user_id = p.owner_user_id
      AND c.name = p.category
)
WHERE p.category_id IS NULL
  AND p.category IS NOT NULL
  AND TRIM(p.category) <> '';

UPDATE products p
SET unit_id = (
    SELECT u.id
    FROM product_units u
    WHERE u.owner_user_id = p.owner_user_id
      AND u.name = p.unit
)
WHERE p.unit_id IS NULL
  AND p.unit IS NOT NULL
  AND TRIM(p.unit) <> '';

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_categories_owner_name ON product_categories(owner_user_id, name);
CREATE UNIQUE INDEX IF NOT EXISTS uq_product_units_owner_name ON product_units(owner_user_id, name);
CREATE UNIQUE INDEX IF NOT EXISTS uq_partner_groups_owner_type_name ON partner_groups(owner_user_id, partner_type, name);
CREATE INDEX IF NOT EXISTS idx_partner_contacts_owner_type_partner ON partner_contacts(owner_user_id, partner_type, partner_id);
CREATE INDEX IF NOT EXISTS idx_products_owner_category_id ON products(owner_user_id, category_id);
CREATE INDEX IF NOT EXISTS idx_products_owner_unit_id ON products(owner_user_id, unit_id);
CREATE INDEX IF NOT EXISTS idx_customers_owner_group_id ON customers(owner_user_id, group_id);
CREATE INDEX IF NOT EXISTS idx_suppliers_owner_group_id ON suppliers(owner_user_id, group_id);

ALTER TABLE partner_groups DROP CONSTRAINT IF EXISTS chk_partner_groups_partner_type;
ALTER TABLE partner_contacts DROP CONSTRAINT IF EXISTS chk_partner_contacts_partner_type;
ALTER TABLE partner_contacts DROP CONSTRAINT IF EXISTS uq_partner_contacts_primary;
ALTER TABLE products DROP CONSTRAINT IF EXISTS fk_products_category_id;
ALTER TABLE products DROP CONSTRAINT IF EXISTS fk_products_unit_id;
ALTER TABLE customers DROP CONSTRAINT IF EXISTS fk_customers_group_id;
ALTER TABLE suppliers DROP CONSTRAINT IF EXISTS fk_suppliers_group_id;

ALTER TABLE partner_groups
    ADD CONSTRAINT chk_partner_groups_partner_type
    CHECK (partner_type IN ('customer', 'supplier'));

ALTER TABLE partner_contacts
    ADD CONSTRAINT chk_partner_contacts_partner_type
    CHECK (partner_type IN ('customer', 'supplier'));

CREATE UNIQUE INDEX IF NOT EXISTS uq_partner_contacts_primary
    ON partner_contacts(owner_user_id, partner_type, partner_id, is_primary)
    WHERE is_primary;

ALTER TABLE products
    ADD CONSTRAINT fk_products_category_id
    FOREIGN KEY (category_id) REFERENCES product_categories(id);

ALTER TABLE products
    ADD CONSTRAINT fk_products_unit_id
    FOREIGN KEY (unit_id) REFERENCES product_units(id);

ALTER TABLE customers
    ADD CONSTRAINT fk_customers_group_id
    FOREIGN KEY (group_id) REFERENCES partner_groups(id);

ALTER TABLE suppliers
    ADD CONSTRAINT fk_suppliers_group_id
    FOREIGN KEY (group_id) REFERENCES partner_groups(id);
