<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { ChevronLeft, ChevronRight, Eye, RefreshCw, Search, ShieldAlert } from 'lucide-vue-next'
import AdminLayout from '@/features/admin/components/AdminLayout.vue'
import AdminPanelState from '@/features/admin/components/AdminPanelState.vue'
import { useSession } from '@/app/stores/session'
import { fetchAdminAuditEvents, type AdminAuditEvent } from '@/shared/api/admin'

const session = useSession(); const action = ref(''); const resourceType = ref(''); const page = ref(0); const size = 20; const items = ref<AdminAuditEvent[]>([]); const total = ref(0); const hasNext = ref(false); const loading = ref(false); const error = ref<unknown>(null)
const message = () => error.value instanceof Error ? error.value.message : '管理员审计读取失败'
async function load() { if (!session.token.value) { error.value = new Error('管理员会话已失效'); return }; loading.value = true; error.value = null; try { const result = await fetchAdminAuditEvents(session.token.value, { action: action.value || undefined, resourceType: resourceType.value || undefined, page: page.value, size }); items.value = result.items; total.value = result.total; hasNext.value = result.hasNext } catch (cause) { error.value = cause } finally { loading.value = false } }
function previous() { if (page.value > 0) { page.value -= 1; void load() } }; function next() { if (hasNext.value) { page.value += 1; void load() } }; function date(value?: string) { return value ? new Date(value).toLocaleString('zh-CN', { dateStyle: 'medium', timeStyle: 'short' }) : '-' }
watch([action, resourceType], () => { page.value = 0; void load() }); onMounted(load)
</script>
<template>
  <AdminLayout active-id="audit"><section class="admin-page-v2"><header class="admin-page-v2__header"><div><div class="admin-page-v2__crumb">Admin / <strong>Audit</strong></div><h1>操作审计</h1><p>查询管理员动作、资源和服务端返回的结果摘要。</p></div><button class="admin-button-v2" type="button" :disabled="loading" @click="load"><RefreshCw :class="{ 'is-spinning': loading }" aria-hidden="true" />刷新</button></header><div v-if="error" class="admin-error-v2" role="alert"><ShieldAlert aria-hidden="true" /><span>{{ message() }}</span><button type="button" @click="load">重试</button></div><div class="admin-grid"><article class="admin-card-v2 admin-span-12"><div class="admin-card-v2__header"><div><h2>事件记录</h2><p>正文与敏感字段默认不在审计列表中返回。</p></div><Eye aria-hidden="true" /></div><div class="admin-card-v2__body admin-toolbar"><label class="admin-field"><Search aria-hidden="true" /><input v-model="action" type="search" placeholder="动作，例如 read_run" aria-label="筛选动作" /></label><label class="admin-field"><select v-model="resourceType" aria-label="资源类型"><option value="">全部资源</option><option value="RUN">运行</option><option value="USER">用户</option><option value="STORE">门店</option><option value="CONFIG">配置</option></select></label></div><AdminPanelState v-if="loading" state="loading" title="正在读取审计事件" /><AdminPanelState v-else-if="error" state="error" :message="message()" @retry="load" /><AdminPanelState v-else-if="items.length === 0" state="empty" title="当前范围暂无审计事件" message="服务端没有返回当前筛选条件下的审计记录。" /><div v-else class="admin-table-wrap"><table class="admin-table-v2"><thead><tr><th>时间</th><th>动作</th><th>资源</th><th>操作者</th><th>结果</th><th>摘要</th></tr></thead><tbody><tr v-for="item in items" :key="item.eventId"><td>{{ date(item.occurredAt) }}</td><td><strong>{{ item.action }}</strong></td><td>{{ item.resourceType || '-' }}<small>{{ item.resourceId || '-' }}</small></td><td><code>{{ item.actorAdminUserId || '-' }}</code></td><td><span class="admin-status-v2" :class="`admin-status-v2--${/success|ok|allow/i.test(item.result || '') ? 'ok' : /fail|deny/i.test(item.result || '') ? 'bad' : 'warn'}`">{{ item.result || '未知' }}</span></td><td>{{ item.summary || '无摘要' }}</td></tr></tbody></table></div><footer v-if="!loading && !error && total > 0" class="admin-pagination"><span>第 {{ page + 1 }} 页 · {{ total }} 条</span><button type="button" :disabled="page === 0" aria-label="上一页" @click="previous"><ChevronLeft aria-hidden="true" /></button><button type="button" :disabled="!hasNext" aria-label="下一页" @click="next"><ChevronRight aria-hidden="true" /></button></footer></article></div></section></AdminLayout>
</template>
