CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    type INTEGER NOT NULL DEFAULT 1,
    balance DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    status INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    notes VARCHAR(255),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS account_transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    transfer_no VARCHAR(64) NOT NULL,
    from_account_id BIGINT NOT NULL,
    to_account_id BIGINT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    fee DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    status INTEGER NOT NULL DEFAULT 1,
    notes VARCHAR(255),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS bill_fund_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    bill_type VARCHAR(32) NOT NULL,
    bill_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    link_type INTEGER NOT NULL DEFAULT 1,
    notes VARCHAR(255),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS cash_change_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    order_type VARCHAR(32) NOT NULL,
    order_id BIGINT NOT NULL,
    receivable DOUBLE PRECISION NOT NULL,
    received DOUBLE PRECISION NOT NULL,
    change_amount DOUBLE PRECISION NOT NULL,
    account_id BIGINT,
    status INTEGER NOT NULL DEFAULT 1,
    notes VARCHAR(255),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_code VARCHAR(64) NOT NULL,
    product_name VARCHAR(128) NOT NULL,
    warehouse_id BIGINT,
    quantity_before DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    quantity_change DOUBLE PRECISION NOT NULL,
    quantity_after DOUBLE PRECISION NOT NULL,
    unit_cost DOUBLE PRECISION,
    source_type VARCHAR(32) NOT NULL,
    source_id BIGINT,
    source_no VARCHAR(64),
    notes VARCHAR(255),
    created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_code VARCHAR(64) NOT NULL,
    product_name VARCHAR(128) NOT NULL,
    warehouse_id BIGINT,
    quantity DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    unit_cost DOUBLE PRECISION,
    total_value DOUBLE PRECISION,
    snapshot_date BIGINT NOT NULL,
    created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory_monthly_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_code VARCHAR(64) NOT NULL,
    product_name VARCHAR(128) NOT NULL,
    warehouse_id BIGINT,
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    quantity_in DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    quantity_out DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    quantity_adjust DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    quantity_begin DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    quantity_end DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    total_cost_in DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    total_cost_out DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

ALTER TABLE accounts
    ADD CONSTRAINT uk_accounts_owner_code UNIQUE (owner_user_id, code);

ALTER TABLE accounts
    ADD CONSTRAINT uk_accounts_owner_id UNIQUE (owner_user_id, id);

ALTER TABLE account_transfers
    ADD CONSTRAINT uk_account_transfers_owner_no UNIQUE (owner_user_id, transfer_no);

ALTER TABLE bill_fund_links
    ADD CONSTRAINT fk_bill_fund_links_owner_account FOREIGN KEY (owner_user_id, account_id)
        REFERENCES accounts(owner_user_id, id);

ALTER TABLE account_transfers
    ADD CONSTRAINT fk_account_transfers_owner_from FOREIGN KEY (owner_user_id, from_account_id)
        REFERENCES accounts(owner_user_id, id);

ALTER TABLE account_transfers
    ADD CONSTRAINT fk_account_transfers_owner_to FOREIGN KEY (owner_user_id, to_account_id)
        REFERENCES accounts(owner_user_id, id);

ALTER TABLE cash_change_records
    ADD CONSTRAINT fk_cash_change_records_owner_account FOREIGN KEY (owner_user_id, account_id)
        REFERENCES accounts(owner_user_id, id);

ALTER TABLE inventory_snapshots
    ADD CONSTRAINT uk_inventory_snapshots_owner_product_date UNIQUE (owner_user_id, product_id, snapshot_date);

ALTER TABLE inventory_monthly_stats
    ADD CONSTRAINT uk_inventory_monthly_stats_owner_product_period UNIQUE (owner_user_id, product_id, year, month);

CREATE INDEX idx_accounts_owner ON accounts (owner_user_id);
CREATE INDEX idx_account_transfers_owner ON account_transfers (owner_user_id);
CREATE INDEX idx_bill_fund_links_owner_bill ON bill_fund_links (owner_user_id, bill_type, bill_id);
CREATE INDEX idx_bill_fund_links_owner_account ON bill_fund_links (owner_user_id, account_id);
CREATE INDEX idx_cash_change_records_owner ON cash_change_records (owner_user_id);
CREATE INDEX idx_inventory_ledger_owner_product ON inventory_ledger (owner_user_id, product_id);
CREATE INDEX idx_inventory_ledger_owner_created ON inventory_ledger (owner_user_id, created_at);
CREATE INDEX idx_inventory_snapshots_owner_date ON inventory_snapshots (owner_user_id, snapshot_date);
CREATE INDEX idx_inventory_snapshots_owner_product ON inventory_snapshots (owner_user_id, product_id);
CREATE INDEX idx_inventory_monthly_stats_owner_month ON inventory_monthly_stats (owner_user_id, year, month);
CREATE INDEX idx_inventory_monthly_stats_owner_product ON inventory_monthly_stats (owner_user_id, product_id);
