CREATE TABLE IF NOT EXISTS import_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    requested_by_user_id BIGINT NOT NULL,
    client_id VARCHAR(128) NOT NULL,
    source_type VARCHAR(64) NOT NULL,
    source_uri VARCHAR(512),
    source_checksum VARCHAR(128),
    idempotency_key VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    stage VARCHAR(32) NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    replay_cursor VARCHAR(128),
    summary_json VARCHAR(4000),
    options_json VARCHAR(4000),
    failure_code VARCHAR(64),
    failure_message VARCHAR(1024),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    started_at BIGINT,
    finished_at BIGINT,
    last_heartbeat_at BIGINT
);

ALTER TABLE import_jobs
    ADD CONSTRAINT uk_import_jobs_owner_idempotency UNIQUE (owner_user_id, idempotency_key);

CREATE INDEX idx_import_jobs_owner_created ON import_jobs(owner_user_id, created_at DESC);
CREATE INDEX idx_import_jobs_owner_status ON import_jobs(owner_user_id, status, updated_at DESC);
CREATE INDEX idx_import_jobs_owner_client ON import_jobs(owner_user_id, client_id);
