CREATE TABLE IF NOT EXISTS media_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    asset_type VARCHAR(32) NOT NULL,
    storage_provider VARCHAR(32) NOT NULL,
    bucket_name VARCHAR(128),
    object_key VARCHAR(512) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(128) NOT NULL,
    size_bytes BIGINT NOT NULL,
    checksum VARCHAR(128),
    width INTEGER,
    height INTEGER,
    metadata_json VARCHAR(4000),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE INDEX idx_media_assets_owner_created ON media_assets(owner_user_id, created_at DESC);
CREATE UNIQUE INDEX uk_media_assets_owner_object_key ON media_assets(owner_user_id, object_key);

CREATE TABLE IF NOT EXISTS media_bindings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    asset_id BIGINT NOT NULL,
    target_type VARCHAR(64) NOT NULL,
    target_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    CONSTRAINT fk_media_bindings_asset FOREIGN KEY (asset_id) REFERENCES media_assets(id)
);

CREATE INDEX idx_media_bindings_owner_target ON media_bindings(owner_user_id, target_type, target_id, sort_order, id);
CREATE UNIQUE INDEX uk_media_bindings_owner_target_asset ON media_bindings(owner_user_id, asset_id, target_type, target_id);

CREATE TABLE IF NOT EXISTS agent_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    latest_summary VARCHAR(1000),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    last_message_at BIGINT
);

CREATE INDEX idx_agent_conversations_owner_updated ON agent_conversations(owner_user_id, updated_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS agent_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    conversation_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    message_type VARCHAR(32) NOT NULL,
    content VARCHAR(4000) NOT NULL,
    structured_data_json VARCHAR(4000),
    created_at BIGINT NOT NULL,
    CONSTRAINT fk_agent_messages_conversation FOREIGN KEY (conversation_id) REFERENCES agent_conversations(id)
);

CREATE INDEX idx_agent_messages_owner_conversation_created ON agent_messages(owner_user_id, conversation_id, created_at ASC, id ASC);

CREATE TABLE IF NOT EXISTS agent_drafts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    conversation_id BIGINT,
    draft_type VARCHAR(32) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content_json VARCHAR(4000) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT fk_agent_drafts_conversation FOREIGN KEY (conversation_id) REFERENCES agent_conversations(id)
);

CREATE INDEX idx_agent_drafts_owner_updated ON agent_drafts(owner_user_id, updated_at DESC, id DESC);
