CREATE TABLE IF NOT EXISTS agent_run_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    conversation_id BIGINT,
    run_id VARCHAR(64) NOT NULL,
    audit_id VARCHAR(128) NOT NULL,
    trace_id VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    mode VARCHAR(64),
    llm_status VARCHAR(64),
    plan_source VARCHAR(64),
    tool_count INTEGER,
    error_code VARCHAR(64),
    error_message VARCHAR(1000),
    started_at BIGINT NOT NULL,
    completed_at BIGINT,
    updated_at BIGINT NOT NULL,
    event_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_agent_run_audits_conversation FOREIGN KEY (conversation_id) REFERENCES agent_conversations(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_agent_run_audits_run_id ON agent_run_audits(run_id);
CREATE INDEX IF NOT EXISTS idx_agent_run_audits_owner_started ON agent_run_audits(owner_user_id, started_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_agent_run_audits_owner_status ON agent_run_audits(owner_user_id, status, updated_at DESC);

CREATE TABLE IF NOT EXISTS agent_run_audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    event_id VARCHAR(128) NOT NULL,
    seq INTEGER NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    payload_json TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    CONSTRAINT fk_agent_run_audit_events_run FOREIGN KEY (run_id) REFERENCES agent_run_audits(run_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_agent_run_audit_events_event_id ON agent_run_audit_events(event_id);
CREATE INDEX IF NOT EXISTS idx_agent_run_audit_events_run_seq ON agent_run_audit_events(run_id, seq ASC, id ASC);
