CREATE TABLE IF NOT EXISTS purchase_returns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    return_no VARCHAR(64) NOT NULL,
    purchase_order_id BIGINT,
    supplier_id BIGINT,
    supplier_name VARCHAR(128),
    total_amount DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    refund_amount DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    status INTEGER NOT NULL DEFAULT 0,
    notes VARCHAR(255),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

ALTER TABLE purchase_returns ADD CONSTRAINT uk_purchase_returns_owner_return_no UNIQUE (owner_user_id, return_no);
CREATE INDEX idx_purchase_returns_owner ON purchase_returns(owner_user_id);
CREATE INDEX idx_purchase_returns_purchase_order ON purchase_returns(purchase_order_id);
CREATE INDEX idx_purchase_returns_status ON purchase_returns(owner_user_id, status);

CREATE TABLE IF NOT EXISTS purchase_return_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    return_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    product_code VARCHAR(64),
    product_name VARCHAR(128),
    quantity DOUBLE PRECISION NOT NULL,
    unit_cost DOUBLE PRECISION NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    created_at BIGINT NOT NULL
);

CREATE INDEX idx_purchase_return_items_owner ON purchase_return_items(owner_user_id);
CREATE INDEX idx_purchase_return_items_return ON purchase_return_items(return_id);

CREATE TABLE IF NOT EXISTS purchase_return_refunds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    return_id BIGINT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    method INTEGER NOT NULL,
    reference_no VARCHAR(128),
    created_at BIGINT NOT NULL
);

CREATE INDEX idx_purchase_return_refunds_owner ON purchase_return_refunds(owner_user_id);
CREATE INDEX idx_purchase_return_refunds_return ON purchase_return_refunds(return_id);
