CREATE TABLE IF NOT EXISTS product_price_levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS product_supplier_relations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    purchase_priority INTEGER NOT NULL DEFAULT 0,
    last_purchase_price DOUBLE PRECISION,
    notes VARCHAR(255),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS price_level_values_json VARCHAR(4000);

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_price_levels_owner_code
    ON product_price_levels(owner_user_id, code);

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_price_levels_owner_name
    ON product_price_levels(owner_user_id, name);

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_supplier_relations_owner_product_supplier
    ON product_supplier_relations(owner_user_id, product_id, supplier_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_product_supplier_relations_owner_product_default
    ON product_supplier_relations(owner_user_id, product_id, is_default)
    WHERE is_default;

CREATE INDEX IF NOT EXISTS idx_product_supplier_relations_owner_product
    ON product_supplier_relations(owner_user_id, product_id);

CREATE INDEX IF NOT EXISTS idx_product_supplier_relations_owner_supplier
    ON product_supplier_relations(owner_user_id, supplier_id);

ALTER TABLE product_supplier_relations
    DROP CONSTRAINT IF EXISTS fk_product_supplier_relations_product_id;

ALTER TABLE product_supplier_relations
    DROP CONSTRAINT IF EXISTS fk_product_supplier_relations_supplier_id;

ALTER TABLE product_supplier_relations
    ADD CONSTRAINT fk_product_supplier_relations_product_id
    FOREIGN KEY (product_id) REFERENCES products(id);

ALTER TABLE product_supplier_relations
    ADD CONSTRAINT fk_product_supplier_relations_supplier_id
    FOREIGN KEY (supplier_id) REFERENCES suppliers(id);
